# Generated by Django 4.2.5 on 2023-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='app_album_viewer.album'),
        ),
    ]
