# Generated by Django 4.2.5 on 2023-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0002_remove_song_album_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(null=True, to='app_album_viewer.album'),
        ),
    ]
