# Generated by Django 4.2.5 on 2023-11-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Album',
            new_name='album',
        ),
    ]
