# Generated by Django 4.2.5 on 2023-12-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0006_rename_album_comment_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(blank=True, to='app_album_viewer.album'),
        ),
    ]
