# Generated by Django 4.2.5 on 2023-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0008_alter_album_description_alter_album_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
