# Generated by Django 4.2.5 on 2023-12-06 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0011_remove_userprofile_email_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, default='sample_data/default-cover.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.date(2023, 12, 6)),
        ),
    ]
